name: ðŸ— Website analysis

on:
  schedule:
    # All sunday at 1AM
    - cron:  '0 1 * * 0'
  workflow_dispatch:

env:
  CHROME_PATH: /usr/bin/google-chrome-stable
  DAREBOOST_API_TOKEN: ${{ secrets.DAREBOOST_API_TOKEN }}
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  deploy:
    name: Website analysis
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Heart packages for analysis
        id: install-heart-for-analysis
        run: |
          cd ci/conf
          pnpm init
          pnpm install -D @fabernovel/heart-cli @fabernovel/heart-dareboost @fabernovel/heart-greenit @fabernovel/heart-lighthouse @fabernovel/heart-observatory @fabernovel/heart-slack @fabernovel/heart-ssllabs-server

      - name: Install Chrome
        id: install-chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update
          apt-get install --yes google-chrome-stable

      - name: ðŸ”¬ Analyze the website with Dareboost
        id: dareboost-analyze
        run: |
          cd ci/conf
          pnpm exec heart dareboost --file dareboost.json

      - name: ðŸ”¬ Analyze the website with Google Lighthouse
        id: lighthouse-analyze
        run: |
          cd ci/conf
          pnpm exec heart lighthouse --file lighthouse.json

      - name: ðŸ”¬ Analyze the website with Mozilla Observatory
        run: |
          cd ci/conf
          pnpm exec heart observatory --file observatory.json

      - name: ðŸ”¬ Analyze the website with GreenIT
        run: |
          cd ci/conf
          pnpm exec heart greenit --file greenit.json

      - name: ðŸ”¬ Analyze the website with SSL Labs Server
        run: |
          cd ci/conf
          pnpm exec heart ssllabs-server --file ssllabs-server.json
